name: Playwright Tests
on:
  workflow_dispatch:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Send Email
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.MAIL_USER}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: ${{secrets.MAIL_USER}}
        # Required sender full name (address can be skipped):
        from: ${{secrets.MAIL_USER}}
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        # html_body: file://README.html
        # # Optional carbon copy recipients:
        # cc: kyloren@example.com,leia@example.com
        # # Optional blind carbon copy recipients:
        # bcc: r2d2@example.com,hansolo@example.com
        # Optional recipient of the email response:
        # reply_to: luke@example.com
        # Optional Message ID this message is replying to:
        # in_reply_to: <random-luke@example.com>
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: false
        # Optional converting Markdown to HTML (set content_type to text/html too):
        # convert_markdown: true
        # Optional attachments:
        # attachments: attachments.zip,git.diff,./dist/static/*.js
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: high
        # # Optional nodemailerlog: true/false
        # nodemailerlog: false
        # # Optional nodemailerdebug: true/false if true lognodem will also be set true
        # nodemailerdebug: false
